name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: lablabs/setup-tflint@v1
    - name: Install Checkov
      id: checkov
      run: |
        pip3 install -U checkov
    - name: Install terraform-docs
      run: |
        curl -sSLo ./terraform-docs.tar.gz https://terraform-docs.io/dl/v0.16.0/terraform-docs-v0.16.0-$(uname)-amd64.tar.gz
        tar -xzf terraform-docs.tar.gz
        chmod +x terraform-docs
        mv terraform-docs /usr/local/bin

    - name: install tfsec
      run: |
        curl -L "$(curl -s https://api.github.com/repos/aquasecurity/tfsec/releases/latest | grep -o -E "https://.*?_linux_amd64.tar.gz")" > tfsec.tar.gz
        tar -xzf tfsec.tar.gz tfsec
        tar -xzf tfsec.tar.gz tfsec-checkgen && rm tfsec.tar.gz
        install tfsec /usr/local//bin && rm tfsec
        install tfsec-checkgen /usr/local//bin && rm tfsec-checkgen
    - name: install terrascan
      run: |
        curl -L "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
        tar -xf terrascan.tar.gz terrascan && rm terrascan.tar.gz
        install terrascan /usr/local/bin && rm terrascan
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${  }|${  }
    - uses: pre-commit/action@v3.0.0
