name: Module release process action
on:
  pull_request:
    types: [closed]

jobs:
  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and push new tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          default_bump: patch
          default_prerelease_bump: false
          custom_release_rules: |
            "fix:patch:Bug Fixes,style:patch:Code Style,refactor:patch:Refactor,chore:patch:Chores,feat:minor:Features,release:major:Release"
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      - uses: BobAnkh/auto-generate-changelog@v1.2.3
        with:
          REPO_NAME: 'vfontanella/vfontanella'
          ACCESS_TOKEN: ${{secrets.GH_TOKEN}}
          PATH: 'CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
          TYPE: 'feat:Feature,fix:Bug Fixes,style:Code Style,chore:Chores,docs:Documentation,refactor:Refactor,perf:Performance Improvements,release:Release'

permissions:
  contents: write
  pull-requests: write